server:
  port: 18005
# 数据源配置
spring:
  # datasoure默认使用JDBC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'xxx!'
    url: jdbc:mysql://${MYSQL_HOST:192.168.7.171}:${MYSQL_PORT:3306}/zipkin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  sleuth:
    enabled: false
  rabbitmq:
    host: 192.168.7.171
    port: 5672
    password: 'guest'
    username: guest

zipkin:
  storage:
    type: mysql

logging:
  file: logs/zipkin-db.log